#!/usr/bin/env bash

# ------------------------------------------------------------
# Deploy Tascorr web app to a generic web‑hosting account
# ------------------------------------------------------------
# This script assumes the host provides:
#   • SSH access (or a terminal emulator in the control panel)
#   • Node.js (v18 or newer) and npm
#   • Write permission to the target directory
#   • Ability to run background processes (pm2 or nohup)
#   • SQLite (default DB) works on the host file system
# ------------------------------------------------------------

set -e

# ---- CONFIG ------------------------------------------------
# Change these only if your environment differs
TARGET_DIR="${PWD}"               # Directory where the script lives – the project root
NODE_VERSION="18"                # Minimum Node version required
PM2_GLOBAL="pm2"                # Name of the pm2 binary (installed globally)
APP_PORT="5005"                  # Port the Express server will listen on
ENV_FILE=".env"
# ------------------------------------------------------------

# Helper: print sections nicely
section() {
  echo "\n=== $1 ==="
}

# ---- PRE‑CHECKS -------------------------------------------
section "Checking prerequisites"

if ! command -v node >/dev/null 2>&1; then
  echo "Error: node not found. Install Node.js (v${NODE_VERSION}+)."
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "Error: npm not found. Install npm (bundled with Node)."
  exit 1
fi

# Verify Node version meets minimum requirement
CURRENT_NODE=$(node -v | sed 's/v//')
if [[ $(printf "%s\n" "$CURRENT_NODE" "$NODE_VERSION" | sort -V | head -n1) != "$NODE_VERSION" ]]; then
  echo "Warning: Detected Node $CURRENT_NODE, but v$NODE_VERSION+ is recommended."
fi

# ---- SETUP ENV ---------------------------------------------
section "Creating .env file"
if [ ! -f "$ENV_FILE" ]; then
  JWT_SECRET=$(openssl rand -base64 48)
  cat > "$ENV_FILE" <<EOF
# Auto‑generated by deploy.sh – adjust if you use a different DB
JWT_SECRET=$JWT_SECRET
PORT=$APP_PORT
DATABASE_URL="file:${TARGET_DIR}/dev.db"
EOF
  echo ".env created with a random JWT secret."
else
  echo ".env already exists – leaving untouched."
fi

# ---- INSTALL DEPENDENCIES -----------------------------------
section "Installing npm dependencies"
# Use npm ci to respect package‑lock and ensure a clean install
npm ci

# ---- BUILD FRONTEND ----------------------------------------
section "Building Vite frontend"
npm run build

# ---- DATABASE MIGRATIONS ----------------------------------
section "Running Prisma migrations"
# Prisma requires the CLI; we use npx to avoid a global install
npx prisma migrate deploy

# ---- START APPLICATION --------------------------------------
section "Starting the server"

# Try to use pm2 first (global install). If unavailable we fall back to nohup.
if command -v $PM2_GLOBAL >/dev/null 2>&1; then
  echo "pm2 detected – launching the app with pm2."
  $PM2_GLOBAL start ./dist/server/server/index.js --name tascorr
  $PM2_GLOBAL save
else
  echo "pm2 not available – using nohup to run in background."
  nohup node ./dist/server/server/index.js > server.log 2>&1 &
  echo "Server started, PID $(pgrep -f ./dist/server/server/index.js)"
fi

section "Deployment complete"
echo "Your app is now running on port $APP_PORT."
if command -v $PM2_GLOBAL >/dev/null 2>&1; then
  echo "Manage it with: $PM2_GLOBAL status | $PM2_GLOBAL restart tascorr | $PM2_GLOBAL stop tascorr"
else
  echo "To stop the app: kill $(pgrep -f ./dist/server/server/index.js)"
fi

# ------------------------------------------------------------
# OPTIONAL: Provide a short Nginx/Apache snippet that proxies
# the /tascorr/ path to the above port.  Most shared hosts have a
# UI for this – you can paste the snippet into the custom config.
# ------------------------------------------------------------
cat <<'NGINX_SNIPPET' > nginx_tascorr.conf
# Nginx snippet for sub‑directory deployment (soft.thinksafe.mv/tascorr/)
location /tascorr/ {
    proxy_pass http://127.0.0.1:${APP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    # Serve static assets from the Vite build directory
    alias ${TARGET_DIR}/dist/;
    try_files $uri $uri/ =404;
}
NGINX_SNIPPET

echo "A ready‑to‑paste Nginx config (nginx_tascorr.conf) was generated in the project root."
