<?php
/**
 * install.php - Web-based interactive installation wizard for Tascorr.
 * Guided installation script for Plesk. Set up database, run schema, write .env,
 * create superadmin, and finalize installation.
 */

// If installer is called via AJAX
if (isset($_GET['action'])) {
    header('Content-Type: application/json');
    $action = $_GET['action'];

    try {
        switch ($action) {
            case 'test_db':
                $data = json_decode(file_get_contents('php://input'), true);
                $host = $data['host'] ?? 'localhost';
                $port = $data['port'] ?? '3306';
                $dbname = $data['dbname'] ?? '';
                $username = $data['username'] ?? '';
                $password = $data['password'] ?? '';

                if (empty($dbname) || empty($username)) {
                    throw new Exception('Database name and username are required.');
                }

                $dsn = "mysql:host=$host;port=$port;dbname=$dbname;charset=utf8mb4";
                $options = [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_TIMEOUT => 5
                ];
                $pdo = new PDO($dsn, $username, $password, $options);
                
                echo json_encode(['success' => true, 'message' => 'Database connection successful.']);
                exit;

            case 'install_schema':
                $data = json_decode(file_get_contents('php://input'), true);
                $host = $data['host'] ?? 'localhost';
                $port = $data['port'] ?? '3306';
                $dbname = $data['dbname'] ?? '';
                $username = $data['username'] ?? '';
                $password = $data['password'] ?? '';

                $dsn = "mysql:host=$host;port=$port;dbname=$dbname;charset=utf8mb4";
                $pdo = new PDO($dsn, $username, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

                if (!file_exists('install.sql')) {
                    throw new Exception('install.sql schema file not found in root.');
                }

                $sql = file_get_contents('install.sql');
                
                // Execute schema. We execute statement by statement or using PDO exec for multi-query
                // Note: PDO exec is capable of executing multiple queries separated by semicolons in pdo_mysql
                $pdo->exec($sql);

                // Fetch created tables to present checklist
                $stmt = $pdo->query("SHOW TABLES");
                $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);

                echo json_encode(['success' => true, 'message' => 'Schema installed successfully.', 'tables' => $tables]);
                exit;

            case 'save_env':
                $data = json_decode(file_get_contents('php://input'), true);
                $host = $data['host'] ?? 'localhost';
                $port = $data['port'] ?? '3306';
                $dbname = $data['dbname'] ?? '';
                $username = $data['username'] ?? '';
                $password = $data['password'] ?? '';

                // Generate random JWT Secret (256-bit representation)
                $jwtSecret = base64_encode(random_bytes(32));

                $envContent = "# =======================================================\n";
                $envContent .= "# Auto-generated by Tascorr Web Installer Wizard\n";
                $envContent .= "# Generated: " . date('Y-m-d H:i:s') . "\n";
                $envContent .= "# =======================================================\n\n";
                $envContent .= "PORT=5005\n";
                $envContent .= "DATABASE_URL=\"mysql://$username:" . urlencode($password) . "@$host:$port/$dbname\"\n";
                $envContent .= "JWT_SECRET=\"$jwtSecret\"\n";
                $envContent .= "NODE_ENV=\"production\"\n";
                $envContent .= "ALLOWED_ORIGINS=\"https://tascorr.thinksafe.mv\"\n";

                if (file_put_contents('.env', $envContent) === false) {
                    throw new Exception('Failed to write .env file. Check directory permissions.');
                }

                // Apply .htaccess security rule blocking direct web access to .env
                $htaccessRule = "<Files .env>\nOrder allow,deny\nDeny from all\n</Files>\n";
                if (file_exists('.htaccess')) {
                    $existing = file_get_contents('.htaccess');
                    if (strpos($existing, '<Files .env>') === false) {
                        file_put_contents('.htaccess', $existing . "\n" . $htaccessRule);
                    }
                } else {
                    file_put_contents('.htaccess', $htaccessRule);
                }

                echo json_encode(['success' => true, 'message' => '.env file successfully generated and secured.']);
                exit;

            case 'create_superadmin':
                $data = json_decode(file_get_contents('php://input'), true);
                $host = $data['host'] ?? 'localhost';
                $port = $data['port'] ?? '3306';
                $dbname = $data['dbname'] ?? '';
                $username = $data['username'] ?? '';
                $password = $data['password'] ?? '';
                
                $saEmail = $data['sa_email'] ?? '';
                $saPassword = $data['sa_password'] ?? '';

                if (empty($saEmail) || empty($saPassword)) {
                    throw new Exception('Superadmin email and password are required.');
                }

                // Password complexity check: 12+ chars, mixed case, number, symbol
                if (strlen($saPassword) < 12) {
                    throw new Exception('Password must be at least 12 characters.');
                }
                if (!preg_match('/[A-Z]/', $saPassword) || !preg_match('/[a-z]/', $saPassword)) {
                    throw new Exception('Password must contain both uppercase and lowercase letters.');
                }
                if (!preg_match('/[0-9]/', $saPassword)) {
                    throw new Exception('Password must contain at least one number.');
                }
                if (!preg_match('/[^a-zA-Z0-9]/', $saPassword)) {
                    throw new Exception('Password must contain at least one symbol/special character.');
                }

                // Hash password using Bcrypt with cost factor 12
                $passwordHash = password_hash($saPassword, PASSWORD_BCRYPT, ['cost' => 12]);

                $dsn = "mysql:host=$host;port=$port;dbname=$dbname;charset=utf8mb4";
                $pdo = new PDO($dsn, $username, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

                // Insert Superadmin User referencing Rank ID 999 (created in install.sql)
                $stmt = $pdo->prepare("INSERT INTO `users` 
                    (`tenant_id`, `email`, `password_hash`, `first_name`, `last_name`, `rank_id`, `status`, `created_at`, `updated_at`) 
                    VALUES (0, ?, ?, 'Global', 'Superadmin', 999, 'active', NOW(), NOW())");
                $stmt->execute([$saEmail, $passwordHash]);

                echo json_encode(['success' => true, 'message' => 'Superadmin account created successfully.']);
                exit;

            case 'seed_data':
                $data = json_decode(file_get_contents('php://input'), true);
                $host = $data['host'] ?? 'localhost';
                $port = $data['port'] ?? '3306';
                $dbname = $data['dbname'] ?? '';
                $username = $data['username'] ?? '';
                $password = $data['password'] ?? '';

                $dsn = "mysql:host=$host;port=$port;dbname=$dbname;charset=utf8mb4";
                $pdo = new PDO($dsn, $username, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

                // Load seed data for evaluation workspace (Tenant 1, Ranks, Users, Departments, Tasks)
                $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
                $pdo->exec("SET @@session.sql_mode = CONCAT(@@session.sql_mode, ',NO_AUTO_VALUE_ON_ZERO');");

                // Seed Tenant 1
                $pdo->exec("INSERT INTO `tenants` (`id`, `name`, `subscriptionTier`, `status`, `created_at`, `updated_at`) VALUES (1, 'Acme Maldives Corp', 1, 'active', NOW(), NOW())");

                // Seed Ranks for Tenant 1
                $pdo->exec("INSERT INTO `ranks` (`id`, `tenant_id`, `title`, `level`, `created_at`, `updated_at`) VALUES
                    (1, 1, 'Administrator', 0, NOW(), NOW()),
                    (2, 1, 'Chief Executive', 1, NOW(), NOW()),
                    (3, 1, 'Deputy Chief Executive', 2, NOW(), NOW()),
                    (4, 1, 'Executive / Director', 3, NOW(), NOW()),
                    (5, 1, 'Department Head', 4, NOW(), NOW()),
                    (6, 1, 'Manager', 5, NOW(), NOW()),
                    (7, 1, 'Employee', 6, NOW(), NOW())");

                // Seed Users
                $hash = password_hash('CompanyAdmin123!', PASSWORD_BCRYPT, ['cost' => 12]);
                $pdo->exec("INSERT INTO `users` (`id`, `tenant_id`, `email`, `password_hash`, `first_name`, `last_name`, `rank_id`, `status`, `created_at`, `updated_at`) VALUES
                    (2, 1, 'admin@company.com', '$hash', 'Company', 'Admin', 1, 'active', NOW(), NOW()),
                    (3, 1, 'head@company.com', '$hash', 'Ahmed', 'Shareef', 5, 'active', NOW(), NOW()),
                    (4, 1, 'employee@company.com', '$hash', 'Sara', 'Zahir', 7, 'active', NOW(), NOW())");

                // Seed Department
                $pdo->exec("INSERT INTO `departments` (`id`, `tenant_id`, `name`, `head_user_id`, `created_at`, `updated_at`) VALUES (1, 1, 'Finance & Accounting', 3, NOW(), NOW())");
                $pdo->exec("UPDATE `users` SET `department_id` = 1 WHERE `id` = 3");
                $pdo->exec("UPDATE `users` SET `department_id` = 1, `manager_id` = 3 WHERE `id` = 4");

                // Seed Tasks
                $pdo->exec("INSERT INTO `tasks` (`id`, `tenant_id`, `title`, `description`, `status`, `priority`, `due_date`, `created_by_id`, `department_id`, `created_at`, `updated_at`, `is_recurring`, `recurrence_interval`) VALUES
                    (1, 1, 'Approve Annual Budget Proposals', 'Review and consolidate target department budgets submitted for next financial year. Ensure calculations are double-checked for margin errors.', 'Under Review', 'Critical', DATE_ADD(NOW(), INTERVAL 10 DAY), 2, 1, NOW(), NOW(), 0, NULL),
                    (2, 1, 'Vendor Contract Setup', 'Set up legal compliance parameters and draft formal software service SLA contract.', 'Blocked', 'High', DATE_SUB(NOW(), INTERVAL 2 DAY), 3, 1, NOW(), NOW(), 0, NULL)");

                // Seed Assignments
                $pdo->exec("INSERT INTO `task_assignments` (`tenant_id`, `task_id`, `user_id`, `assigned_at`, `is_active`) VALUES
                    (1, 1, 4, NOW(), 1),
                    (1, 2, 4, NOW(), 1)");

                // Seed Subtasks
                $pdo->exec("INSERT INTO `subtasks` (`tenant_id`, `task_id`, `title`, `status`, `created_at`, `updated_at`) VALUES
                    (1, 1, 'Gather financial data spreadsheets', 'Completed', NOW(), NOW()),
                    (1, 1, 'Execute compliance audit review', 'Completed', NOW(), NOW()),
                    (1, 1, 'Draft Executive summary notes', 'Pending', NOW(), NOW())");

                // Seed Blocker
                $pdo->exec("INSERT INTO `blockers` (`tenant_id`, `task_id`, `reporter_id`, `description`, `created_at`) VALUES
                    (1, 2, 4, 'Awaiting signed compliance check from legal team.', NOW())");

                $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");

                echo json_encode(['success' => true, 'message' => 'Evaluation seed data loaded successfully.']);
                exit;

            case 'finalize':
                $data = json_decode(file_get_contents('php://input'), true);
                $saEmail = $data['sa_email'] ?? '';
                
                // Write credentials to credentials text file one directory above webroot if possible
                // Otherwise write locally as fallback
                $targetPath = dirname(__DIR__) . '/tascorr-install-credentials.txt';
                $details = "=== TASCORR INSTALLATION DETAILS ===\n";
                $details .= "Installation Date: " . date('Y-m-d H:i:s') . "\n";
                $details .= "Domain: tascorr.thinksafe.mv\n";
                $details .= "Global Superadmin Email: $saEmail\n";
                $details .= "Database Name: " . ($data['dbname'] ?? '') . "\n";
                $details .= "====================================\n";

                @file_put_contents($targetPath, $details);

                // Self delete install.php
                @unlink(__FILE__);

                echo json_encode(['success' => true, 'message' => 'Wizard finalized and deleted. Redirecting...']);
                exit;
        }
    } catch (Exception $e) {
        http_response_code(500);
        echo json_encode(['success' => false, 'message' => $e->getMessage()]);
        exit;
    }
}

// Perform Pre-flight checks for UI
$preflight = [
    'php_version' => [
        'title' => 'PHP Version 7.4+',
        'passed' => version_compare(PHP_VERSION, '7.4.0', '>='),
        'detail' => 'Running PHP ' . PHP_VERSION
    ],
    'pdo_mysql' => [
        'title' => 'PDO MySQL Extension',
        'passed' => extension_loaded('pdo_mysql'),
        'detail' => extension_loaded('pdo_mysql') ? 'Enabled' : 'Missing'
    ],
    'mbstring' => [
        'title' => 'mbstring Extension',
        'passed' => extension_loaded('mbstring'),
        'detail' => extension_loaded('mbstring') ? 'Enabled' : 'Missing'
    ],
    'json' => [
        'title' => 'json Extension',
        'passed' => extension_loaded('json'),
        'detail' => extension_loaded('json') ? 'Enabled' : 'Missing'
    ],
    'fileinfo' => [
        'title' => 'fileinfo Extension',
        'passed' => extension_loaded('fileinfo'),
        'detail' => extension_loaded('fileinfo') ? 'Enabled' : 'Missing'
    ],
    'write_permissions' => [
        'title' => 'Directory Write Permissions',
        'passed' => is_writable(__DIR__),
        'detail' => is_writable(__DIR__) ? 'Writable' : 'Read-only directory'
    ],
    'env_exists' => [
        'title' => '.env File Check',
        'passed' => !file_exists('.env'),
        'detail' => file_exists('.env') ? '.env already exists (Clear it or delete it to proceed)' : 'No pre-existing config'
    ]
];

$allPassed = true;
foreach ($preflight as $check) {
    if (!$check['passed']) {
        $allPassed = false;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tascorr Database Installation Wizard</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #0d0e12;
            --container-bg: rgba(22, 24, 30, 0.75);
            --primary-gradient: linear-gradient(135deg, #7c3aed, #4f46e5);
            --accent-color: #a78bfa;
            --text-color: #e2e8f0;
            --text-muted: #94a3b8;
            --success-color: #10b981;
            --error-color: #ef4444;
            --border-color: rgba(255, 255, 255, 0.08);
            --input-bg: rgba(255, 255, 255, 0.04);
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Outfit', sans-serif;
            background-color: var(--bg-color);
            background-image: 
                radial-gradient(at 0% 0%, rgba(124, 58, 237, 0.1) 0, transparent 50%),
                radial-gradient(at 100% 100%, rgba(79, 70, 229, 0.1) 0, transparent 50%);
            color: var(--text-color);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            overflow-x: hidden;
        }

        .installer-container {
            width: 100%;
            max-width: 650px;
            background: var(--container-bg);
            backdrop-filter: blur(16px);
            border: 1px solid var(--border-color);
            border-radius: 20px;
            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.5);
            padding: 40px;
            position: relative;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .logo-text {
            font-size: 2rem;
            font-weight: 700;
            background: var(--primary-gradient);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 8px;
            letter-spacing: -0.5px;
        }

        .subtitle {
            color: var(--text-muted);
            font-size: 0.95rem;
        }

        .progress-bar-container {
            display: flex;
            justify-content: space-between;
            margin-bottom: 40px;
            position: relative;
        }

        .progress-line {
            position: absolute;
            top: 15px;
            left: 5%;
            width: 90%;
            height: 2px;
            background: rgba(255, 255, 255, 0.08);
            z-index: 1;
        }

        .progress-line-active {
            position: absolute;
            top: 15px;
            left: 5%;
            width: 0%;
            height: 2px;
            background: var(--primary-gradient);
            z-index: 2;
            transition: width 0.4s ease;
        }

        .progress-step {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            background: #1c1d24;
            border: 2px solid rgba(255, 255, 255, 0.1);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 0.85rem;
            font-weight: 600;
            color: var(--text-muted);
            z-index: 3;
            transition: all 0.3s ease;
            position: relative;
        }

        .progress-step.active {
            border-color: var(--accent-color);
            background: var(--bg-color);
            color: var(--text-color);
            box-shadow: 0 0 10px rgba(167, 139, 250, 0.3);
        }

        .progress-step.completed {
            background: var(--success-color);
            border-color: var(--success-color);
            color: white;
        }

        .step-panel {
            display: none;
            animation: fadeIn 0.4s ease;
        }

        .step-panel.active {
            display: block;
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }

        h2 {
            font-size: 1.35rem;
            font-weight: 600;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .check-list {
            list-style: none;
            display: flex;
            flex-direction: column;
            gap: 12px;
            margin-bottom: 30px;
        }

        .check-item {
            background: rgba(255, 255, 255, 0.02);
            border: 1px solid var(--border-color);
            padding: 15px 20px;
            border-radius: 12px;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .check-status {
            display: flex;
            align-items: center;
            gap: 8px;
            font-weight: 500;
        }

        .status-badge {
            padding: 4px 10px;
            border-radius: 6px;
            font-size: 0.75rem;
            font-weight: 600;
        }

        .status-badge.success {
            background: rgba(16, 185, 129, 0.15);
            color: var(--success-color);
        }

        .status-badge.error {
            background: rgba(239, 68, 68, 0.15);
            color: var(--error-color);
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            font-size: 0.85rem;
            color: var(--text-muted);
            margin-bottom: 8px;
            font-weight: 500;
        }

        .form-control {
            width: 100%;
            background: var(--input-bg);
            border: 1px solid var(--border-color);
            border-radius: 10px;
            padding: 12px 16px;
            font-family: inherit;
            color: var(--text-color);
            font-size: 0.95rem;
            transition: all 0.3s;
        }

        .form-control:focus {
            outline: none;
            border-color: var(--accent-color);
            background: rgba(255, 255, 255, 0.08);
            box-shadow: 0 0 0 2px rgba(167, 139, 250, 0.15);
        }

        .btn-container {
            display: flex;
            justify-content: space-between;
            margin-top: 35px;
            gap: 15px;
        }

        .btn {
            padding: 14px 28px;
            border-radius: 10px;
            font-weight: 600;
            font-size: 0.95rem;
            cursor: pointer;
            transition: all 0.3s;
            border: none;
            display: inline-flex;
            align-items: center;
            gap: 8px;
        }

        .btn-primary {
            background: var(--primary-gradient);
            color: white;
            box-shadow: 0 4px 12px rgba(79, 70, 229, 0.3);
        }

        .btn-primary:hover:not(:disabled) {
            transform: translateY(-1px);
            box-shadow: 0 6px 16px rgba(79, 70, 229, 0.4);
        }

        .btn-secondary {
            background: rgba(255, 255, 255, 0.06);
            color: var(--text-color);
            border: 1px solid var(--border-color);
        }

        .btn-secondary:hover:not(:disabled) {
            background: rgba(255, 255, 255, 0.1);
        }

        .btn:disabled {
            opacity: 0.4;
            cursor: not-allowed;
        }

        .alert {
            padding: 15px 20px;
            border-radius: 12px;
            margin-bottom: 25px;
            font-size: 0.9rem;
            line-height: 1.5;
            display: none;
        }

        .alert-error {
            background: rgba(239, 68, 68, 0.1);
            border: 1px solid rgba(239, 68, 68, 0.2);
            color: #fca5a5;
        }

        .alert-success {
            background: rgba(16, 185, 129, 0.1);
            border: 1px solid rgba(16, 185, 129, 0.2);
            color: #a7f3d0;
        }

        .loading-dots {
            display: inline-flex;
            gap: 4px;
        }

        .loading-dots span {
            width: 6px;
            height: 6px;
            border-radius: 50%;
            background: white;
            animation: bounce 1.4s infinite ease-in-out both;
        }

        .loading-dots span:nth-child(1) { animation-delay: -0.32s; }
        .loading-dots span:nth-child(2) { animation-delay: -0.16s; }

        @keyframes bounce {
            0%, 80%, 100% { transform: scale(0); }
            40% { transform: scale(1.0); }
        }

        .table-list {
            max-height: 200px;
            overflow-y: auto;
            border: 1px solid var(--border-color);
            border-radius: 10px;
            padding: 15px;
            background: rgba(0, 0, 0, 0.2);
            font-family: monospace;
            font-size: 0.85rem;
            color: var(--text-muted);
            margin-bottom: 20px;
        }

        .table-list-item {
            display: flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 6px;
        }

        .table-list-item::before {
            content: "✔";
            color: var(--success-color);
        }

        .checkbox-container {
            display: flex;
            align-items: flex-start;
            gap: 10px;
            cursor: pointer;
            margin-top: 10px;
        }

        .checkbox-container input {
            margin-top: 4px;
        }

        .info-card {
            background: rgba(124, 58, 237, 0.05);
            border: 1px solid rgba(124, 58, 237, 0.15);
            border-radius: 12px;
            padding: 16px 20px;
            font-size: 0.88rem;
            line-height: 1.5;
            color: var(--accent-color);
            margin-bottom: 25px;
        }
    </style>
</head>
<body>

<div class="installer-container">
    <div class="header">
        <div class="logo-text">TASCORR</div>
        <div class="subtitle">Database Configuration & Deployment Wizard</div>
    </div>

    <!-- Progress Indicator -->
    <div class="progress-bar-container">
        <div class="progress-line"></div>
        <div class="progress-line-active" id="progress-line-active"></div>
        <div class="progress-step active" data-step="1">1</div>
        <div class="progress-step" data-step="2">2</div>
        <div class="progress-step" data-step="3">3</div>
        <div class="progress-step" data-step="4">4</div>
        <div class="progress-step" data-step="5">5</div>
        <div class="progress-step" data-step="6">6</div>
    </div>

    <!-- Error Alert Box -->
    <div class="alert alert-error" id="error-alert"></div>
    <div class="alert alert-success" id="success-alert"></div>

    <!-- STEP 1: PREFLIGHT CHECKS -->
    <div class="step-panel active" id="panel-1">
        <h2>System Compatibility Audit</h2>
        <ul class="check-list">
            <?php foreach ($preflight as $key => $check): ?>
                <li class="check-item">
                    <div>
                        <div style="font-weight: 500;"><?= htmlspecialchars($check['title']) ?></div>
                        <div style="font-size: 0.8rem; color: var(--text-muted); margin-top: 2px;">
                            <?= htmlspecialchars($check['detail']) ?>
                        </div>
                    </div>
                    <span class="status-badge <?= $check['passed'] ? 'success' : 'error' ?>">
                        <?= $check['passed'] ? 'PASSED' : 'FAILED' ?>
                    </span>
                </li>
            <?php endforeach; ?>
        </ul>

        <div class="btn-container" style="justify-content: flex-end;">
            <button class="btn btn-primary" id="btn-to-step2" <?= !$allPassed ? 'disabled' : '' ?>>
                Continue to Database Configuration &rarr;
            </button>
        </div>
    </div>

    <!-- STEP 2: DATABASE CONFIG -->
    <div class="step-panel" id="panel-2">
        <h2>Configure MySQL/MariaDB Connection</h2>
        <div style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 25px;">
            Specify the credentials for the MySQL database you created in the Plesk controller panel.
        </div>

        <div class="form-group">
            <label for="db-host">Database Hostname (typically localhost)</label>
            <input type="text" class="form-control" id="db-host" value="localhost">
        </div>

        <div class="form-group">
            <label for="db-port">Port (typically 3306)</label>
            <input type="text" class="form-control" id="db-port" value="3306">
        </div>

        <div class="form-group">
            <label for="db-name">Database Name</label>
            <input type="text" class="form-control" id="db-name" placeholder="e.g. tascorr_db">
        </div>

        <div class="form-group">
            <label for="db-username">Username</label>
            <input type="text" class="form-control" id="db-username" placeholder="e.g. tascorr_user">
        </div>

        <div class="form-group">
            <label for="db-password">Password</label>
            <input type="password" class="form-control" id="db-password" placeholder="Enter database password">
        </div>

        <div class="btn-container">
            <button class="btn btn-secondary" onclick="goToStep(1)">&larr; Back</button>
            <button class="btn btn-primary" id="btn-test-db">
                Test Connection &amp; Continue
            </button>
        </div>
    </div>

    <!-- STEP 3: SCHEMA INSTALLATION -->
    <div class="step-panel" id="panel-3">
        <h2>Schema &amp; Tables Import</h2>
        <div style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 20px;">
            The installer is ready to build the relational architecture from <code style="color: var(--accent-color);">install.sql</code> into the database.
        </div>

        <div class="table-list" id="tables-list-container" style="display: none;"></div>

        <div class="btn-container">
            <button class="btn btn-secondary" onclick="goToStep(2)">&larr; Back</button>
            <button class="btn btn-primary" id="btn-run-schema">
                Execute Schema Install
            </button>
        </div>
    </div>

    <!-- STEP 4: ENVIRONMENT GENERATION -->
    <div class="step-panel" id="panel-4">
        <h2>Generate System Environment</h2>
        <div style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 25px;">
            We will now generate the production configuration file <code style="color: var(--accent-color);">.env</code>.
            A secured entry will also be placed in your web server rules config.
        </div>

        <div class="info-card">
            We will automatically write database connection parameters and generate a secure random 256-bit JWT signing secret key into your configuration file.
        </div>

        <div class="btn-container">
            <button class="btn btn-secondary" disabled>&larr; Back</button>
            <button class="btn btn-primary" id="btn-gen-env">
                Write Environment Config
            </button>
        </div>
    </div>

    <!-- STEP 5: SUPERADMIN CREATION -->
    <div class="step-panel" id="panel-5">
        <h2>Register Global Superadministrator</h2>
        <div style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 25px;">
            Create the primary administrative credential for Tascorr. This user operates in the global management context.
        </div>

        <div class="form-group">
            <label for="sa-email">Superadmin Email Address</label>
            <input type="email" class="form-control" id="sa-email" placeholder="superadmin@domain.com">
        </div>

        <div class="form-group">
            <label for="sa-password">Superadmin Password</label>
            <input type="password" class="form-control" id="sa-password" placeholder="Enter secure password">
            <div style="font-size: 0.75rem; color: var(--text-muted); margin-top: 6px;">
                Password must be at least 12 characters and contain uppercase, lowercase, numbers, and symbols.
            </div>
        </div>

        <div class="btn-container">
            <button class="btn btn-secondary" disabled>&larr; Back</button>
            <button class="btn btn-primary" id="btn-create-sa">
                Create Account &amp; Proceed
            </button>
        </div>
    </div>

    <!-- STEP 6: SEED & COMPLETE -->
    <div class="step-panel" id="panel-6">
        <h2>Bootstrap &amp; Finalization</h2>
        <div style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 25px;">
            Your database infrastructure is set up. You can optionally seed data for testing purposes.
        </div>

        <div class="form-group">
            <label class="checkbox-container">
                <input type="checkbox" id="seed-checkbox" checked>
                <div>
                    <strong>Load Evaluation Demo Workspace Workspace</strong>
                    <div style="font-size: 0.8rem; color: var(--text-muted); margin-top: 4px;">
                        Includes a pre-configured tenant workspace (Acme Maldives Corp), ranks, initial team members, and demo tasks. Recommended for testing.
                    </div>
                </div>
            </label>
        </div>

        <div class="btn-container">
            <button class="btn btn-secondary" disabled>&larr; Back</button>
            <button class="btn btn-primary" id="btn-finalize">
                Finish &amp; Start Platform
            </button>
        </div>
    </div>
</div>

<script>
    // State Store
    const dbConfig = {
        host: 'localhost',
        port: '3306',
        dbname: '',
        username: '',
        password: ''
    };

    let currentStep = 1;
    const totalSteps = 6;
    let saEmailValue = '';

    function showSpinner(button, text) {
        button.disabled = true;
        button.dataset.originalHtml = button.innerHTML;
        button.innerHTML = text + ' <div class="loading-dots"><span></span><span></span><span></span></div>';
    }

    function hideSpinner(button) {
        button.disabled = false;
        button.innerHTML = button.dataset.originalHtml;
    }

    function showAlert(id, text, type) {
        const alert = document.getElementById(id);
        alert.innerText = text;
        alert.className = 'alert alert-' + type;
        alert.style.display = 'block';
    }

    function clearAlerts() {
        document.getElementById('error-alert').style.display = 'none';
        document.getElementById('success-alert').style.display = 'none';
    }

    function goToStep(step) {
        clearAlerts();
        document.getElementById('panel-' + currentStep).classList.remove('active');
        document.querySelector('.progress-step[data-step="' + currentStep + '"]').classList.remove('active');
        if (currentStep < step) {
            document.querySelector('.progress-step[data-step="' + currentStep + '"]').classList.add('completed');
        }

        currentStep = step;
        document.getElementById('panel-' + currentStep).classList.add('active');
        document.querySelector('.progress-step[data-step="' + currentStep + '"]').classList.add('active');
        
        // Progress active line width calculation
        const percent = ((currentStep - 1) / (totalSteps - 1)) * 90;
        document.getElementById('progress-line-active').style.width = percent + '%';
    }

    // Step 1 Click
    document.getElementById('btn-to-step2').addEventListener('click', () => {
        goToStep(2);
    });

    // Step 2 Click (Test DB Connection)
    document.getElementById('btn-test-db').addEventListener('click', async (e) => {
        clearAlerts();
        
        dbConfig.host = document.getElementById('db-host').value;
        dbConfig.port = document.getElementById('db-port').value;
        dbConfig.dbname = document.getElementById('db-name').value;
        dbConfig.username = document.getElementById('db-username').value;
        dbConfig.password = document.getElementById('db-password').value;

        showSpinner(e.target, 'Connecting to server');

        try {
            const response = await fetch('install.php?action=test_db', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(dbConfig)
            });
            const res = await response.json();
            if (res.success) {
                showAlert('success-alert', 'Connection success! Proceeding...', 'success');
                setTimeout(() => goToStep(3), 1000);
            } else {
                showAlert('error-alert', res.message || 'Connection failed.', 'error');
            }
        } catch (err) {
            showAlert('error-alert', 'Network error or connection timeout.', 'error');
        } finally {
            hideSpinner(e.target);
        }
    });

    // Step 3 Click (Run Schema SQL)
    document.getElementById('btn-run-schema').addEventListener('click', async (e) => {
        clearAlerts();
        showSpinner(e.target, 'Installing schema tables');

        try {
            const response = await fetch('install.php?action=install_schema', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(dbConfig)
            });
            const res = await response.json();
            if (res.success) {
                // Show imported tables
                const container = document.getElementById('tables-list-container');
                container.innerHTML = '<strong>Tables Configured:</strong><br>';
                res.tables.forEach(table => {
                    const item = document.createElement('div');
                    item.className = 'table-list-item';
                    item.innerText = table;
                    container.appendChild(item);
                });
                container.style.display = 'block';

                showAlert('success-alert', 'All tables populated successfully.', 'success');
                setTimeout(() => goToStep(4), 2000);
            } else {
                showAlert('error-alert', res.message || 'Execution error.', 'error');
            }
        } catch (err) {
            showAlert('error-alert', 'Execution error or request failure.', 'error');
        } finally {
            hideSpinner(e.target);
        }
    });

    // Step 4 Click (Generate Env Config)
    document.getElementById('btn-gen-env').addEventListener('click', async (e) => {
        clearAlerts();
        showSpinner(e.target, 'Writing configuration');

        try {
            const response = await fetch('install.php?action=save_env', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(dbConfig)
            });
            const res = await response.json();
            if (res.success) {
                showAlert('success-alert', 'Configuration written to .env.', 'success');
                setTimeout(() => goToStep(5), 1500);
            } else {
                showAlert('error-alert', res.message || 'Writing failed.', 'error');
            }
        } catch (err) {
            showAlert('error-alert', 'Network request failed.', 'error');
        } finally {
            hideSpinner(e.target);
        }
    });

    // Step 5 Click (Register Superadmin)
    document.getElementById('btn-create-sa').addEventListener('click', async (e) => {
        clearAlerts();
        saEmailValue = document.getElementById('sa-email').value;
        const saPassword = document.getElementById('sa-password').value;

        if (!saEmailValue || !saPassword) {
            showAlert('error-alert', 'Please enter both email and password.', 'error');
            return;
        }

        showSpinner(e.target, 'Creating administrator account');

        try {
            const response = await fetch('install.php?action=create_superadmin', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    ...dbConfig,
                    sa_email: saEmailValue,
                    sa_password: saPassword
                })
            });
            const res = await response.json();
            if (res.success) {
                showAlert('success-alert', 'Superadmin registered successfully.', 'success');
                setTimeout(() => goToStep(6), 1500);
            } else {
                showAlert('error-alert', res.message || 'Creation failed.', 'error');
            }
        } catch (err) {
            showAlert('error-alert', 'Network request failed.', 'error');
        } finally {
            hideSpinner(e.target);
        }
    });

    // Step 6 Click (Finalize)
    document.getElementById('btn-finalize').addEventListener('click', async (e) => {
        clearAlerts();
        const loadSeed = document.getElementById('seed-checkbox').checked;
        
        showSpinner(e.target, 'Finishing installation');

        try {
            // Optional Seeding
            if (loadSeed) {
                const seedResponse = await fetch('install.php?action=seed_data', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(dbConfig)
                });
                const seedRes = await seedResponse.json();
                if (!seedRes.success) {
                    showAlert('error-alert', seedRes.message || 'Seeding failed. Proceeding to finalize anyway.', 'error');
                    await new Promise(resolve => setTimeout(resolve, 2000));
                }
            }

            // Finalize & Self Delete
            const finalizeResponse = await fetch('install.php?action=finalize', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    ...dbConfig,
                    sa_email: saEmailValue
                })
            });
            const finRes = await finalizeResponse.json();
            if (finRes.success) {
                showAlert('success-alert', 'Installation Complete! Self-deleting installer... Redirecting to login shortly.', 'success');
                setTimeout(() => {
                    window.location.href = 'https://tascorr.thinksafe.mv';
                }, 3000);
            } else {
                showAlert('error-alert', finRes.message || 'Finalization failed.', 'error');
                hideSpinner(e.target);
            }
        } catch (err) {
            showAlert('error-alert', 'Error finalizing installation.', 'error');
            hideSpinner(e.target);
        }
    });
</script>
</body>
</html>
