<?php
/**
 * install-cli.php - Command-line alternative database installation script.
 * Can be run via SSH to bootstrap database config and schema.
 */

if (php_sapi_name() !== 'cli') {
    die("This script can only be run from the command line.\n");
}

function prompt($message, $default = '', $secret = false) {
    echo $message . ($default ? " [$default]" : "") . ": ";
    if ($secret) {
        // Hide password typing on unix platforms
        if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
            system('stty -echo');
        }
        $input = trim(fgets(STDIN));
        if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
            system('stty echo');
            echo "\n";
        }
    } else {
        $input = trim(fgets(STDIN));
    }
    return $input === '' ? $default : $input;
}

echo "=============================================\n";
echo " TASCORR DATABASE INSTALLER (CLI MODE)       \n";
echo "=============================================\n\n";

// Step 1: Pre-flight checks
echo "Running pre-flight compatibility audits...\n";
$issues = [];
if (version_compare(PHP_VERSION, '7.4.0', '<')) {
    $issues[] = "- PHP version must be 7.4.0+ (Running: " . PHP_VERSION . ")";
}
foreach (['pdo_mysql', 'mbstring', 'json', 'fileinfo'] as $ext) {
    if (!extension_loaded($ext)) {
        $issues[] = "- PHP extension '$ext' is missing.";
    }
}
if (!is_writable(__DIR__)) {
    $issues[] = "- Application root directory is not writable.";
}
if (file_exists('.env')) {
    $issues[] = "- A .env file already exists. Delete or back it up to continue.";
}

if (!empty($issues)) {
    echo "\n❌ INSTALLATION BLOCKED due to the following compatibility issues:\n";
    echo implode("\n", $issues) . "\n\n";
    exit(1);
}
echo "✔ All compatibility audits passed successfully.\n\n";

// Step 2: Database config
echo "--- Step 1: Configure Database Connection ---\n";
$host = prompt("Database Host (typically localhost)", "localhost");
$port = prompt("Database Port (typically 3306)", "3306");
$dbname = prompt("Database Name");
$username = prompt("Database Username");
$password = prompt("Database Password", "", true);

if (empty($dbname) || empty($username)) {
    echo "❌ Error: Database name and username are required.\n";
    exit(1);
}

echo "Testing connection...\n";
try {
    $dsn = "mysql:host=$host;port=$port;dbname=$dbname;charset=utf8mb4";
    $options = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_TIMEOUT => 5
    ];
    $pdo = new PDO($dsn, $username, $password, $options);
    echo "✔ Connection established successfully.\n\n";
} catch (Exception $e) {
    echo "❌ Connection failed: " . $e->getMessage() . "\n";
    exit(1);
}

// Step 3: Run schema
echo "--- Step 2: Import Database Schema ---\n";
if (!file_exists('install.sql')) {
    echo "❌ Error: Schema file 'install.sql' not found in root.\n";
    exit(1);
}
echo "Executing install.sql script...\n";
try {
    $sql = file_get_contents('install.sql');
    $pdo->exec($sql);
    echo "✔ Relational database tables generated.\n\n";
} catch (Exception $e) {
    echo "❌ Error importing schema: " . $e->getMessage() . "\n";
    exit(1);
}

// Step 4: Write Env
echo "--- Step 3: Generate Environment Configuration ---\n";
$jwtSecret = base64_encode(random_bytes(32));
$envContent = "# =======================================================\n";
$envContent .= "# Auto-generated by Tascorr CLI Installer\n";
$envContent .= "# Generated: " . date('Y-m-d H:i:s') . "\n";
$envContent .= "# =======================================================\n\n";
$envContent .= "PORT=5005\n";
$envContent .= "DATABASE_URL=\"mysql://$username:" . urlencode($password) . "@$host:$port/$dbname\"\n";
$envContent .= "JWT_SECRET=\"$jwtSecret\"\n";
$envContent .= "NODE_ENV=\"production\"\n";
$envContent .= "ALLOWED_ORIGINS=\"https://tascorr.thinksafe.mv\"\n";

if (file_put_contents('.env', $envContent) === false) {
    echo "❌ Error: Could not write .env file.\n";
    exit(1);
}
echo "✔ File .env generated.\n";

// Secure with htaccess
$htaccessRule = "<Files .env>\nOrder allow,deny\nDeny from all\n</Files>\n";
if (file_exists('.htaccess')) {
    $existing = file_get_contents('.htaccess');
    if (strpos($existing, '<Files .env>') === false) {
        file_put_contents('.htaccess', $existing . "\n" . $htaccessRule);
    }
} else {
    file_put_contents('.htaccess', $htaccessRule);
}
echo "✔ Web security restrictions applied.\n\n";

// Step 5: Superadmin
echo "--- Step 4: Create Global Superadministrator Account ---\n";
$saEmail = '';
while (true) {
    $saEmail = prompt("Global Superadmin Email");
    if (filter_var($saEmail, FILTER_VALIDATE_EMAIL)) break;
    echo "❌ Invalid email format. Try again.\n";
}

$saPassword = '';
while (true) {
    $saPassword = prompt("Global Superadmin Password", "", true);
    
    $passed = true;
    if (strlen($saPassword) < 12) {
        echo "- Password must be 12+ characters.\n";
        $passed = false;
    }
    if (!preg_match('/[A-Z]/', $saPassword) || !preg_match('/[a-z]/', $saPassword)) {
        echo "- Password must contain both upper and lower case letters.\n";
        $passed = false;
    }
    if (!preg_match('/[0-9]/', $saPassword)) {
        echo "- Password must contain numbers.\n";
        $passed = false;
    }
    if (!preg_match('/[^a-zA-Z0-9]/', $saPassword)) {
        echo "- Password must contain special characters.\n";
        $passed = false;
    }

    if ($passed) break;
    echo "❌ Password complexity requirements not met. Try again.\n";
}

$passwordHash = password_hash($saPassword, PASSWORD_BCRYPT, ['cost' => 12]);

try {
    $stmt = $pdo->prepare("INSERT INTO `users` 
        (`tenant_id`, `email`, `password_hash`, `first_name`, `last_name`, `rank_id`, `status`, `created_at`, `updated_at`) 
        VALUES (0, ?, ?, 'Global', 'Superadmin', 999, 'active', NOW(), NOW())");
    $stmt->execute([$saEmail, $passwordHash]);
    echo "✔ Global Superadmin registered.\n\n";
} catch (Exception $e) {
    echo "❌ Error registering Superadmin: " . $e->getMessage() . "\n";
    exit(1);
}

// Step 6: Optional Seeding
echo "--- Step 5: Seed Evaluation Database ---\n";
$seedCheck = prompt("Do you want to seed evaluation demo workspace? (y/n)", "y");
if (strtolower($seedCheck) === 'y') {
    echo "Seeding evaluation workspace data...\n";
    try {
        $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
        $pdo->exec("SET @@session.sql_mode = CONCAT(@@session.sql_mode, ',NO_AUTO_VALUE_ON_ZERO');");

        $pdo->exec("INSERT INTO `tenants` (`id`, `name`, `subscriptionTier`, `status`, `created_at`, `updated_at`) VALUES (1, 'Acme Maldives Corp', 1, 'active', NOW(), NOW())");
        $pdo->exec("INSERT INTO `ranks` (`id`, `tenant_id`, `title`, `level`, `created_at`, `updated_at`) VALUES
            (1, 1, 'Administrator', 0, NOW(), NOW()),
            (2, 1, 'Chief Executive', 1, NOW(), NOW()),
            (3, 1, 'Deputy Chief Executive', 2, NOW(), NOW()),
            (4, 1, 'Executive / Director', 3, NOW(), NOW()),
            (5, 1, 'Department Head', 4, NOW(), NOW()),
            (6, 1, 'Manager', 5, NOW(), NOW()),
            (7, 1, 'Employee', 6, NOW(), NOW())");

        $hash = password_hash('CompanyAdmin123!', PASSWORD_BCRYPT, ['cost' => 12]);
        $pdo->exec("INSERT INTO `users` (`id`, `tenant_id`, `email`, `password_hash`, `first_name`, `last_name`, `rank_id`, `status`, `created_at`, `updated_at`) VALUES
            (2, 1, 'admin@company.com', '$hash', 'Company', 'Admin', 1, 'active', NOW(), NOW()),
            (3, 1, 'head@company.com', '$hash', 'Ahmed', 'Shareef', 5, 'active', NOW(), NOW()),
            (4, 1, 'employee@company.com', '$hash', 'Sara', 'Zahir', 7, 'active', NOW(), NOW())");

        $pdo->exec("INSERT INTO `departments` (`id`, `tenant_id`, `name`, `head_user_id`, `created_at`, `updated_at`) VALUES (1, 1, 'Finance & Accounting', 3, NOW(), NOW())");
        $pdo->exec("UPDATE `users` SET `department_id` = 1 WHERE `id` = 3");
        $pdo->exec("UPDATE `users` SET `department_id` = 1, `manager_id` = 3 WHERE `id` = 4");

        $pdo->exec("INSERT INTO `tasks` (`id`, `tenant_id`, `title`, `description`, `status`, `priority`, `due_date`, `created_by_id`, `department_id`, `created_at`, `updated_at`, `is_recurring`, `recurrence_interval`) VALUES
            (1, 1, 'Approve Annual Budget Proposals', 'Review and consolidate target department budgets submitted for next financial year. Ensure calculations are double-checked for margin errors.', 'Under Review', 'Critical', DATE_ADD(NOW(), INTERVAL 10 DAY), 2, 1, NOW(), NOW(), 0, NULL),
            (2, 1, 'Vendor Contract Setup', 'Set up legal compliance parameters and draft formal software service SLA contract.', 'Blocked', 'High', DATE_SUB(NOW(), INTERVAL 2 DAY), 3, 1, NOW(), NOW(), 0, NULL)");

        $pdo->exec("INSERT INTO `task_assignments` (`tenant_id`, `task_id`, `user_id`, `assigned_at`, `is_active`) VALUES
            (1, 1, 4, NOW(), 1),
            (1, 2, 4, NOW(), 1)");

        $pdo->exec("INSERT INTO `subtasks` (`tenant_id`, `task_id`, `title`, `status`, `created_at`, `updated_at`) VALUES
            (1, 1, 'Gather financial data spreadsheets', 'Completed', NOW(), NOW()),
            (1, 1, 'Execute compliance audit review', 'Completed', NOW(), NOW()),
            (1, 1, 'Draft Executive summary notes', 'Pending', NOW(), NOW())");

        $pdo->exec("INSERT INTO `blockers` (`tenant_id`, `task_id`, `reporter_id`, `description`, `created_at`) VALUES
            (1, 2, 4, 'Awaiting signed compliance check from legal team.', NOW())");

        $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");
        echo "✔ Seed data loaded successfully.\n\n";
    } catch (Exception $e) {
        echo "❌ Seeding failed: " . $e->getMessage() . "\n";
    }
}

// Step 7: Finalize
echo "--- Finalizing Installation ---\n";
$targetPath = dirname(__DIR__) . '/tascorr-install-credentials.txt';
$details = "=== TASCORR INSTALLATION DETAILS ===\n";
$details .= "Installation Date: " . date('Y-m-d H:i:s') . "\n";
$details .= "Domain: tascorr.thinksafe.mv\n";
$details .= "Global Superadmin Email: $saEmail\n";
$details .= "Database Name: $dbname\n";
$details .= "====================================\n";

@file_put_contents($targetPath, $details);
echo "✔ Summary written to: $targetPath\n";

// Deleting file
@unlink(__FILE__);
echo "✔ Installer self-deleted for security.\n\n";
echo "=== TASCORR INSTALLATION COMPLETED SUCCESSFULLY ===\n";
echo "Redirect to: https://tascorr.thinksafe.mv to log in!\n";
